name: Test
on: [push]

jobs:
  test:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'true'
      - name: Test xmake
        shell: powershell
        run: |
          choco install xmake -y --no-progress
          echo "--- AFTER INSTALL ---"
          where.exe xmake
          if ($LASTEXITCODE -ne 0) { echo "xmake not in PATH" }
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          where.exe xmake
          if ($LASTEXITCODE -eq 0) { xmake --version }
